function cellInfo = vvbusinenv(varargin) 
% VVBUSINENV returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'VVCEnv', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'BaroPress', 1, 'double', 'real', 'Sample', 'Fixed', 0, [], sprintf('pascal'), ''}; ...
{'AmbTemp', 1, 'double', 'real', 'Sample', 'Fixed', 0, [], sprintf('kelvin'), ''}; ...
{'Wind', 3, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), sprintf('Wind veloicty in the global inertial frame')}; ...
{'Grade', 1, 'double', 'real', 'Sample', 'Fixed', 0, [], sprintf('deg'), ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
