function cellInfo = vvbusoutvehfdbk(varargin) 
% VVBUSOUTVEHFDBK returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'VVCVehFdbk', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'Driver', 1, 'Bus: Driver', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Body', 1, 'Bus: Body', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Driveline', 1, 'Bus: Driveline', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'Acc', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'ax', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('gee'), ''}; ...
{'ay', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('gee'), ''}; ...
{'az', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('gee'), ''}; ...
{'xddot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s^2'), ''}; ...
{'yddot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s^2'), ''}; ...
{'zddot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s^2'), ''}; ...
    } ...
  } ...
  { ... 
    'Ang', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'phi', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'theta', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'psi', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
    } ...
  } ...
  { ... 
    'AngAcc', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'pdot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s^2'), ''}; ...
{'qdot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s^2'), ''}; ...
{'rdot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s^2'), ''}; ...
    } ...
  } ...
  { ... 
    'AngVel', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'p', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'q', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'r', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
    } ...
  } ...
  { ... 
    'BdyFrm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'Cg', 1, 'Bus: CgB', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'Body', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'InertFrm', 1, 'Bus: InertFrm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BdyFrm', 1, 'Bus: BdyFrm', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'CgB', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'Disp', 1, 'Bus: DispB', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Vel', 1, 'Bus: VelB', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AngVel', 1, 'Bus: AngVel', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Acc', 1, 'Bus: Acc', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AngAcc', 1, 'Bus: AngAcc', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'CgI', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'Disp', 1, 'Bus: DispI', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Vel', 1, 'Bus: VelI', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Ang', 1, 'Bus: Ang', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'DispB', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'x', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'y', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'z', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
    } ...
  } ...
  { ... 
    'DispI', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'X', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'Y', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'Z', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
    } ...
  } ...
  { ... 
    'Driveline', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'EngSpd', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rpm'), ''}; ...
{'EMSpd', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rpm'), ''}; ...
{'TransGear', 1, 'int8', 'real', 'Sample', 'Fixed', [], [], sprintf('one'), ''}; ...
    } ...
  } ...
  { ... 
    'Driver', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'SteerFdbk', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'AccelFdbk', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('one'), ''}; ...
{'DecelFdbk', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('one'), ''}; ...
{'GearFdbk', 1, 'int8', 'real', 'Sample', 'Fixed', [], [], sprintf('one'), ''}; ...
{'IgnFdbk', 1, 'int8', 'real', 'Sample', 'Fixed', [], [], sprintf('one'), ''}; ...
    } ...
  } ...
  { ... 
    'InertFrm', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'Cg', 1, 'Bus: CgI', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Geom', 1, 'Bus: CgI', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'VelB', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'xdot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'ydot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'zdot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
    } ...
  } ...
  { ... 
    'VelI', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'Xdot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'Ydot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'Zdot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
