function cellInfo = vvbusindrvref(varargin) 
% VVBUSINDRVREF returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'VVCDrvRef', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'LngRef', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), sprintf('Longitudinal reference velocity')}; ...
{'LtrRef', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'XRef', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), sprintf('X reference pose')}; ...
{'YRef', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), sprintf('Y reference pose')}; ...
{'PhiRef', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), sprintf('Confirmation needed on coords and angular range / units (yaw angle or phi for angular reference)')}; ...
{'CurvRef', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('1/m'), sprintf('Reference path curvature')}; ...
{'CurvGradRef', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('1/m^2'), sprintf('reference curvature gradient (as a function of station)')}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
