function cellInfo = vvbusenv(varargin) 
% VVBUSENV returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'VVCEnvGnd', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'BaroPress', 1, 'double', 'real', 'Sample', 'Fixed', 0, [], sprintf('pascal'), ''}; ...
{'AmbTemp', 1, 'double', 'real', 'Sample', 'Fixed', 0, [], sprintf('kelvin'), ''}; ...
{'Wind', 3, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), sprintf('Wind veloicty in the global inertial frame')}; ...
{'Grade', 1, 'double', 'real', 'Sample', 'Fixed', 0, [], sprintf('deg'), ''}; ...
{'Gnd', 1, 'Bus: VVCInGndSTI4w', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'VVCGndSTI4w', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'X', 4, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'Y', 4, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'Z', 4, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'lambda_mux', 4, 'double', 'real', 'Sample', 'Fixed', 0, [], sprintf('one'), ''}; ...
{'lambda_muy', 4, 'double', 'real', 'Sample', 'Fixed', 0, [], sprintf('one'), ''}; ...
{'VX', 4, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'VY', 4, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'VZ', 4, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'DCM', [3 3 4], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'OmegaX', 4, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'OmegaY', 4, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'OmegaZ', 4, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'dZdX', 4, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('one'), ''}; ...
{'dZdY', 4, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('one'), ''}; ...
    } ...
  } ...
  { ... 
    'VVCGndSTI6w', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'X', 6, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'Y', 6, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'Z', 6, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'lambda_mux', 6, 'double', 'real', 'Sample', 'Fixed', 0, [], sprintf('one'), ''}; ...
{'lambda_muy', 6, 'double', 'real', 'Sample', 'Fixed', 0, [], sprintf('one'), ''}; ...
{'VX', 6, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'VY', 6, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'VZ', 6, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'DCM', [3 3 6], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'OmegaX', 6, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'OmegaY', 6, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'OmegaZ', 6, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'dZdX', 6, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('one'), ''}; ...
{'dZdY', 6, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('one'), ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
